title: Ivan Ludvig's Blog
author:
  name: IvanLudvig
  email: ivanludvigdev@gmail.com
description:

show_excerpts: false

permalink: /:categories/:title

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      permalink: /:categories/:title
  - scope:
      path: "travel/_posts"
      type: posts
    values:
      permalink: /:categories/:year/:title
      categories: travel

minima:
  skin: classic
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: IvanLudvigDev
    github:  IvanLudvig
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    flickr:   ivanludvig
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    telegram: IvanLudvig
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

url: "https://ivanludvig.dev"
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-paginate 
 - jekyll-redirect-from
